export enum CounterState {
  POMODORO_RUNNING = 'POMODORO_RUNNING',
  BREAK_RUNNING = 'BREAK_RUNNING',
  POMODORO_END = 'POMODORO_END',
  BREAK_END = 'BREAK_END',
  POMODORO_PAUSE = 'POMODORO_PAUSE',
  BREAK_PAUSE = 'BREAK_PAUSE',
}
