export enum SettingsAction {
  GET_SETTINGS = "GET_SETTINGS",
  GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS",
  GET_SETTINGS_ERROR = "GET_SETTINGS_ERROR",

  SAVE_SETTINGS = "SAVE_SETTINGS",
  SAVE_SETTINGS_SUCCESS = "SAVE_SETTINGS_SUCCESS",
  SAVE_SETTINGS_ERROR = "SAVE_SETTINGS_ERROR",
}
